### ISSUE TITLE
When using two colorpickers, the alpha-selector background color is identical

### ISSUE THREAD

**Issue by JDemler** [simonh1000/elm-colorpicker#5]
When using two colorpickers at the same time, the background of the second alpha selector is always the one of the first:
![screenshot from 2018-12-06 01-58-42](https://user-images.githubusercontent.com/12686782/49553992-87e14500-f8fa-11e8-8c93-0cf4747175c8.png)

See this [ellie-example](https://ellie-app.com/45ykGMfGwyya1)

**Comment by simonh1000** [comment]
Hmmm, I see what you mean. I can see what the issue is, but not sure how to fix it yet, other than to require the user to name each colorpicker with an `init` function. Will reflect further

**Comment by JDemler** [comment]
So the problem is an id clash?
How about giving each colorpicker an uuid on init?

https://package.elm-lang.org/packages/danyx23/elm-uuid/latest/

**Comment by simonh1000** [comment]
That would need a lot of wiring up, because random generators are not pure.
I think the easiest will be to let the user do it with an init function. I
thought about an init for the other bug you reported but decided that I
could get to a good result with just a patch anyway
Simon

**Comment by simonh1000** [comment]
Ok, so I have a solution, that will just be a patch update - I'll switch to html+css for this picker. It partially works on my computer, but will need some more work to finalise. You can snag a copy on the sh/two-pickers branch if you need in the short run

**Comment by JDemler** [comment]
Thanks for the quick fix without a breaking change!
