### ISSUE TITLE
Example code missing dependency

### ISSUE THREAD

**Issue by tesk9** [simonh1000/elm-colorpicker#6]
It wasn't immediately obvious to me  that `avh4/elm-color` also needs to be installed & imported in order for the example code to run.

Perhaps something like:
```
import Html exposing (Html)
import ColorPicker 
import Color exposing (Color)
```
might make it more clear that the example relies on `elm-color` in particular?

**Comment by simonh1000** [comment]
hmm, I seem to have messed something up in the config. Users should not need to install elm-color themselves if it is listed as a transitive dependency correctly. Let me take a look

**Comment by simonh1000** [comment]
Hi, I can see that the instructions in example/README.md looked generic, but they were correct. I have simplified them though so the message is clearer. Let me know what you think.

You specific proposal for an import is already at https://github.com/simonh1000/elm-colorpicker/blob/master/example/src/Main.elm#L4
