### ISSUE TITLE
hex2Color and color2Hex relies on 255 color format

### ISSUE THREAD

**Issue by barlindhaug** [simonh1000/elm-colorpicker#7]
Thanks for making this package, I use it for my Elm-powered knitting pattern designer.

I found a bug in the hex conversion functions, since elm-hex needs a value between 0 and 255 (for colors), it will not work when using the values directly from `Color` which is now between 0 and 1. `color2Hex` can be fixed by multiplying with 255 in the `List.map` and `hex2Color` by using `Color.rgb255` instead of `Color.rgb`.

I can make a pull request attempting to fix this, but since they are no longer used internally and elm-color has a `toCssString` function. You might want to remove them altogether. Then you can also drop the elm-hex dependency.

**Comment by simonh1000** [comment]
thanks for reporting - let me take a look

**Comment by simonh1000** [comment]
I decided to follow your suggestion - 2.0.0 fixes this issue

**Comment by simonh1000** [comment]
by the way - if you have any feature requests do let me know.

**Comment by barlindhaug** [comment]
Thank you!
