### ISSUE TITLE
Opacity slider does not reflect color

### ISSUE THREAD

**Issue by janwirth** [simonh1000/elm-colorpicker#8]
It reflects only hue - not brightness or saturation.

<img width="219" alt="image" src="https://user-images.githubusercontent.com/7485959/66714873-c1a59680-edbc-11e9-87ed-770891823d39.png">

**Comment by simonh1000** [comment]
fixed in 2.0.1 - thanks for the report

**Comment by janwirth** [comment]
Awesome! Thanks. I wrote a PR yesterday but it was interesting just digging into it.

**Comment by simonh1000** [comment]
I screwed up and missed the code change in the publish. You will need 2.0.2 now
