### ISSUE TITLE
Can we make this completely stateless

### ISSUE THREAD

**Issue by janwirth** [simonh1000/elm-colorpicker#9]
The state of the colorpicker is only for tracking the mouse if I am not mistaken.

If we use `MouseEvent.button` or `MouseEvent.which` for safari, we can simplify the colorpicker even more.

https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button

**Comment by simonh1000** [comment]
hmm, we still need to put a couple of overlays on the various backgrounds to mark the current selected. Interesitng question whether the two bottom ones could be replaced with range inputs. Not sure about the 2D one though

**Comment by simonh1000** [comment]
and I've long wondered whether I should make the size flexible, and thus part of the model (I suppose it could be passed as a param every time)

**Comment by janwirth** [comment]
The implementation notes that hue gets lost in low-saturation RGB values. I think that would make this thread obsolete.

BTW have you thought about making this awesome tool a web component? I was literally looking for days for a good color picker web components until I found this elm version. Thank you!

**Comment by simonh1000** [comment]
interesting question - I'm working more and more with webcomponents now, but hadn't thought about this

**Comment by janwirth** [comment]
Literally all the other ones are disappointing. The closest one I found is pickr but it lacks type-checking. If we only could find some way to make web components type check.

It would probably required an elm package + an npm package. The elm package provides type-safe functions to produce nodes/attribs/props and the npm package provides the implemetation.
